server:
  port: 80
logging:
  level:
    com.hallen.springcloud: debug
spring:
  application:
    name: cloud-consumer-service
#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka