server:
  port: 8001

spring:
  application:
    name: cloud-pament-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

#mybatis配置
mybatis:
  mapper-locations: classpath:mappings/*/*.xml
  type-aliases-package: com.hallen.springcloud.entities
