server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

#mybatis配置
mybatis:
  mapper-locations: classpath:mappings/*/*.xml
  type-aliases-package: com.hallen.springcloud.entities

#eureka配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      集群后面加就行
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true
#    eureka客户端发送心跳频率(s),默认30
    lease-renewal-interval-in-seconds: 30
#    eureka服务端接收到最后一次心跳后的等待时间上限(s),超时剔除服务,默认90
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.hallen.springcloud: debug
